#+TITLE: Ch01. Probability
#+STARTUP: overview
#+STARTUP: indent
#+OPTIONS: \n: t

* Link to the chapter online
[[https://allendowney.github.io/ThinkBayes2/chap01.html][Chapter 1]]

* Warning
*The content of this file may be incorrect, erroneous and/or harmful. Use it at Your own risk.*

* Data Files
** gss_bayes
[[https://raw.githubusercontent.com/AllenDowney/BiteSizeBayes/master/gss_bayes.csv][Link to the data file (gss_bayes.csv) online]]
* Environment

#+BEGIN_SRC

println("Let's go.")

#+END_SRC

#+BEGIN_SRC

cd(joinpath(homedir(), "Desktop", "julia/luzne_zadanka/book4/ch01")

#+END_SRC

#+BEGIN_SRC

using Pkg
Pkg.activate(".")
Pkg.status()

#+END_SRC

* Imports

#+BEGIN_SRC

import CSV as Csv
import DataFrames as Dfs
import Statistics as St
import StatsBase as Sb

#+END_SRC

* 1.1. Linda the Banker

From the book, originally from [[https://en.wikipedia.org/wiki/Conjunction_fallacy][Amos Tversky and Daniel Kahneman]].

#+BEGIN_QUOTE

Linda is 31 years old, single, outspoken, and very bright. She majored in philosophy. As a student, she was deeply concerned with issues of discrimination and social justice, and also participated in anti-nuclear demonstrations. Which is more probable?

1. Linda is a bank teller.
2. Linda is a bank teller and is active in the feminist movement.

#+END_QUOTE

* 1.2. Probability

#+BEGIN_SRC

gss = Csv.read("./gss_bayes.csv", Dfs.DataFrame);
first(gss, 3)

#+END_SRC

The columns are:
+ caseid: Respondent identifier.
+ year: Year when the respondent was surveyed.
+ age: Respondent’s age when surveyed.
+ sex: Male or female.
+ polviews: Political views on a range from liberal to conservative.
+ partyid: Political party affiliation, Democrat, Independent, or Republican.
+ indus10: Code for the industry the respondent works in.

* 1.3 Fraction of Bankers
code for banking and related activities is 6870

#+BEGIN_SRC

banker = gss.indus10 .== 6870;
sum(banker)
St.mean(banker) # prob banker

#+END_SRC

* 1.4. The probability function


#+BEGIN_SRC

function getProb(a::Bv)::Flt
    return St.mean(a)
end

#+END_SRC


#+BEGIN_SRC

getProb(banker)

#+END_SRC

#+BEGIN_SRC

gss.sex |> unique # 1 - male, 2 - female
female = gss.sex .== 2;
getProb(female)

#+END_SRC

* 1.5. Political Views and Parties (polviews)

polviews:
1 - extremely liberal, 2 - liberal, 3. slightly liberal,
4 -moderate, 5 - slightly conservative, etc.

#+BEGIN_SRC

liberal = gss.polviews .<= 3;
getProb(liberal)

#+END_SRC

partyid:
0 - strong democrat, 1 - not strong democrat,
2 - independent, near democrat, 3 - independent, etc.

#+BEGIN_SRC

democrat = gss.partyid .<= 1;
getProb(democrat)

#+END_SRC

* 1.6. Conjunction

#+BEGIN_SRC

getProb(banker)

#+END_SRC


#+BEGIN_SRC

getProb(democrat)

#+END_SRC

#+BEGIN_SRC

getProb(banker .&& democrat)
getProb(democrat .&& banker)

#+END_SRC

#+BEGIN_SRC

getProb(banker .&& democrat) == getProb(democrat .&& banker)

#+END_SRC

* 1.7. Conditional Probability

#+BEGIN_SRC

# P(democrat|liberal)
selected = democrat[liberal]
getProb(selected)

#+END_SRC

#+BEGIN_SRC

# P(female|banker)
selected = female[banker]
getProb(selected)

#+END_SRC

#+BEGIN_SRC

function getConditionalProb(proposition::Bv, given::Bv)::Flt
    @assert length(proposition) == length(given) "args must be of eql lengths"
    return getProb(proposition[given])
end

#+END_SRC

#+BEGIN_SRC

getConditionalProb(liberal, female)

#+END_SRC

* 1.8. Conditional Probability Is Not Commutative

#+BEGIN_SRC

getConditionalProb(female, banker)

#+END_SRC

#+BEGIN_SRC

getConditionalProb(banker, female)

#+END_SRC

* 1.9. Condition and Conjunction

#+BEGIN_SRC

getConditionalProb(female, liberal .&& democrat)

#+END_SRC

#+BEGIN_SRC

getConditionalProb(liberal .&& female, banker)

#+END_SRC

* 1.10. Laws of Probability

Symbols:

- $P(A)$ - probability that event A
- $P(A\ and\ B)$ - probability of conjunction (both event A and event B occurred)
- $P(A|B)$ - conditional probability of event A given that B happened

Theorems:

1. Using a conjunction we can compute a conditional probability.
2. Using a conditional probability we can compute a conjunction.
3. Using $P(A|B)$ we can compute $P(B|A)$

** 1.10.1. Theorem 1

$P(A|B) = \frac{P(A\ and\ B)}{P(B)}$

Examples

#+BEGIN_SRC

St.mean(female[banker])

#+END_SRC

or

#+BEGIN_SRC

getConditionalProb(female, banker)

#+END_SRC

or

#+BEGIN_SRC

getProb(female .&& banker) / getProb(banker)

#+END_SRC

** 1.10.2. Theorem 2

Start with Theorem 1

$P(A|B) = \frac{P(A\ and\ B)}{P(B)}$

multiply both sites by $P(B)$ to get

$P(A|B) * P(B) = P(A\ and\ B)$

and swap

$P(A\ and\ B) = P(A|B) * P(B)$

and swap to get Theorem 2.

$P(A\ and\ B) =  P(B) * P(A|B)$

Let's test it.

#+BEGIN_SRC

getProb(liberal .&& democrat)

#+END_SRC

which is equal to:

#+BEGIN_SRC

getProb(democrat) * getConditionalProb(liberal, democrat)

#+END_SRC

** 1.10.3. Theorem 3

Since conjunction is commutative:

$P(A\ and\ B) = P(B\ and\ A)$

Then if we apply Theorem 2 to both sides of that conjunction, then we get.

$P(B) * P(A|B) = P(A) * P(B|A)$

Now, we divide both sides by $P(B)$

$\frac{P(B) * P(A|B)}{P(B)} = \frac{P(A) * P(B|A)}{P(B)}$

which gives us Theorem 3 in the form:

$P(A|B) = \frac{P(A) * P(B|A)}{P(B)}$

*We call Theorem 3 the Bayes's Theorem*

Let's check this out in practice.

#+BEGIN_SRC

getConditionalProb(liberal, banker)

#+END_SRC

and the equivalent:

#+BEGIN_SRC

getProb(liberal) * getConditionalProb(banker, liberal) / getProb(banker)

#+END_SRC

* 1.11. The Law of Total Probability

$P(A) + P(B_1\ and\ A) + P(B_2)\ and\ A)$

B1, B2 - two possibilities

Necessary condition: B1, B2 are: mutually exclusive and collectively exhaustive

#+BEGIN_SRC

getProb(banker)

#+END_SRC

#+BEGIN_SRC

male = gss.sex .== 1

getProb(male .&& banker) + getProb(female .&& banker)

#+END_SRC

Applying Theorem 2:

$P(A\ and\ B)  = P(A|B) * P(B)$

to:

$P(A) + P(B_1\ and\ A) + P(B_2\ and\ A)$

after swapping $P(B_i\ and\ A)$ to $P(A\ and\ B_i)$ first (since conjunction/multiplication is commutative) gives us:

$P(A) + P(A\ and\ B_1) + P(A\ and\ B_2)$

prior to substitution of Theorem 2.

After the substitution of Theorem 2 we get:

$P(A)  = P(A|B_1) * P(B_1) + P(A|B_2) * P(B_2)$

equivalently written as:

$P(A)  =  P(B_1) * P(A|B_1) +  P(B_2) * P(A|B_2)$

Let's test it with an example:

#+BEGIN_SRC

getProb(male) * getConditionalProb(banker, male) +
    getProb(female) * getConditionalProb(banker, female)

#+END_SRC

With more than two conditions (more than two Bs) we write the formula as:

$P(A)  = \sum_i P(B_i) * P(A|B_i)$

Which we check for polviews.

#+BEGIN_SRC

B = gss.polviews
bCounts = Sb.countmap(B)
for k in sort(keys(bCounts) |> collect)
    println("$k\t$(bCounts[k])")
end

#+END_SRC

Where 4.0 represents 'Moderate', so prob of a moderate banker is:

#+BEGIN_SRC

getProb(B .== 4) * getConditionalProb(banker, B .== 4)

#+END_SRC

and the prob of banker is:

#+BEGIN_SRC

[getProb(B .== i) * getConditionalProb(banker, B .== i) for i in 1:7] |> sum

#+END_SRC

* 1.12. Summary

The important things are the three Theorems, especially Theorem 3 aka Bayes's theorem:

$P(A|B) = \frac{P(B|A) * P(A)}{P(B)}$

or equivalently

$P(A|B) = \frac{P(A) * P(B|A)}{P(B)}$

and the law of total probability:

$P(A)  = \sum_i P(B_i) * P(A|B_i)$

Which are useful to compute the probability of interest in case we don't have
all the data as we had it here.

* 1.13. Exercises
** 1.13.1. Liberals and Democrats
Calculate P(liberal|democrat)

#+BEGIN_SRC

getConditionalProb(liberal, democrat)

#+END_SRC

and P(democrat|liberal)

#+BEGIN_SRC

getConditionalProb(democrat, liberal)

#+END_SRC

** 1.13.2. Linda the Banker

Calculate P(Linda is a banker), remember she is a female (you know that already)

#+BEGIN_SRC

getConditionalProb(banker, female)

#+END_SRC

Calculate P(Linda is a banker and liberal democrat), remember she is a female (you know that already).

#+BEGIN_SRC

getConditionalProb(banker .&& liberal .&& democrat, female)

#+END_SRC
