#+TITLE: Ch01. Probability
#+STARTUP: overview
#+STARTUP: indent
#+OPTIONS: \n: t

* Link to the chapter online
[[https://allendowney.github.io/ThinkBayes2/chap01.html][Chapter 1]]

* Warning
*The content of this file may be incorrect, erroneous and/or harmful. Use it at Your own risk.*

* Data Files
** gss_bayes
[[https://raw.githubusercontent.com/AllenDowney/BiteSizeBayes/master/gss_bayes.csv][Link to the data file (gss_bayes.csv) online]]
* Environment

#+BEGIN_SRC

println("Let's go.")

#+END_SRC

#+BEGIN_SRC

cd(joinpath(homedir(), "Desktop", "julia/luzne_zadanka/book4/ch01")

#+END_SRC

#+BEGIN_SRC

using Pkg
Pkg.activate(".")
Pkg.status()

#+END_SRC

* Imports

#+BEGIN_SRC

import CSV as Csv
import DataFrames as Dfs
import Statistics as St
import StatsBase as Sb

#+END_SRC

* 1.1. Linda the Banker

From the book, originally from [[https://en.wikipedia.org/wiki/Conjunction_fallacy][with Amos Tversky and Daniel Kahneman]].

#+BEGIN_QUOTE

Linda is 31 years old, single, outspoken, and very bright. She majored in philosophy. As a student, she was deeply concerned with issues of discrimination and social justice, and also participated in anti-nuclear demonstrations. Which is more probable?

1. Linda is a bank teller.
2. Linda is a bank teller and is active in the feminist movement.

#+END_QUOTE

* 1.2. Probability

#+BEGIN_SRC

gss = Csv.read("./gss_bayes.csv", Dfs.DataFrame);
first(gss, 3)

#+END_SRC

The columns are:
+ caseid: Respondent identifier.
+ year: Year when the respondent was surveyed.
+ age: Respondent’s age when surveyed.
+ sex: Male or female.
+ polviews: Political views on a range from liberal to conservative.
+ partyid: Political party affiliation, Democrat, Independent, or Republican.
+ indus10: Code for the industry the respondent works in.

* 1.3 Fraction of Bankers
code for banking and related activities is 6870

#+BEGIN_SRC

banker = gss.indus10 .== 6870;
sum(banker)
St.mean(banker) # prob banker

#+END_SRC

* 1.4 The probability function


#+BEGIN_SRC

function getProb(a::Bv)::Flt
    return St.mean(a)
end

#+END_SRC


#+BEGIN_SRC

getProb(banker)

#+END_SRC

#+BEGIN_SRC

gss.sex |> unique # 1 - male, 2 - female
female = gss.sex .== 2;
getProb(female)

#+END_SRC

* 1.5 Political Views and Parties (polviews)

polviews:
1 - extremely liberal, 2 - liberal, 3. slightly liberal,
4 -moderate, 5 - slightly conservative, etc.

#+BEGIN_SRC

liberal = gss.polviews .<= 3;
getProb(liberal)

#+END_SRC

partyid:
0 - strong democrat, 1 - not strong democrat,
2 - independent, near democrat, 3 - independent, etc.

#+BEGIN_SRC

democrat = gss.partyid .<= 1;
getProb(democrat)

#+END_SRC

* 1.6 Conjunction

#+BEGIN_SRC

getProb(banker)

#+END_SRC


#+BEGIN_SRC

getProb(democrat)

#+END_SRC

#+BEGIN_SRC

getProb(banker .&& democrat)
getProb(democrat .&& banker)

#+END_SRC

#+BEGIN_SRC

getProb(banker .&& democrat) == getProb(democrat .&& banker)

#+END_SRC
